---
# https://access.redhat.com/solutions/34626
- name: Change Default Random Number Generator
  lineinfile:
    dest: "{{ eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -Djava.security.egd=file:/dev/./urandom"
  tags:
    - jboss_bxms

- name: Create Local Maven Directory
  sudo: true
  file:
    path: /opt/jboss-as/.m2
    owner: "{{ jboss_bxms_service_user }}"
    group: "{{ jboss_bxms_service_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_bxms

- name: Copy Maven settings.xml
  copy:
    src: settings.xml
    dest: /opt/jboss-as/.m2/settings.xml
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_user }}"
  tags:
    - jboss_bxms

- name: Set JAVA_OPTS in standalone.conf
  lineinfile:
    dest: "{{ eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -D{{ item.0 }}={{ item.1 }}"
    regexp: "(.*)({{ item.0 }})(.*)"
  with_items:
  - "{{ jboss_bxms_java_opts }}"
  tags:
    - jboss_bxms
